# fly.toml app configuration file generated for restless-glade-433 on 2023-06-20T20:37:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-glade-433"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "3000" 